import { Router, type IRouter } from "express";
import healthRouter from "./health";
import articlesRouter from "./articles";
import settingsRouter from "./settings";
import servicesRouter from "./services";
import packagesRouter from "./packages";
import leadsRouter from "./leads";
import caseStudiesRouter from "./case-studies";
import uploadsRouter from "./uploads";
import socialPostsRouter from "./social-posts";
import aiRouter from "./ai";
import authRouter from "./auth";
import accountsRouter from "./accounts";
import taxesRouter from "./taxes";
import costCentersRouter from "./cost-centers";
import currenciesRouter from "./currencies";
import journalRouter from "./journal";
import dashboardRouter from "./dashboard";
import companyRouter from "./company";
import teamRouter from "./team";
import invitationsRouter from "./invitations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(accountsRouter);
router.use(taxesRouter);
router.use(costCentersRouter);
router.use(currenciesRouter);
router.use(journalRouter);
router.use(dashboardRouter);
router.use(companyRouter);
router.use(teamRouter);
router.use(invitationsRouter);
router.use(articlesRouter);
router.use(settingsRouter);
router.use(servicesRouter);
router.use(packagesRouter);
router.use(leadsRouter);
router.use(caseStudiesRouter);
router.use(uploadsRouter);
router.use(socialPostsRouter);
router.use(aiRouter);

export default router;
