import { Router, type IRouter } from "express";
import healthRouter from "./health";
import articlesRouter from "./articles";
import settingsRouter from "./settings";
import servicesRouter from "./services";
import packagesRouter from "./packages";
import leadsRouter from "./leads";
import caseStudiesRouter from "./case-studies";
import uploadsRouter from "./uploads";
import socialPostsRouter from "./social-posts";
import aiRouter from "./ai";
import authRouter from "./auth";
import accountsRouter from "./accounts";
import taxesRouter from "./taxes";
import costCentersRouter from "./cost-centers";
import currenciesRouter from "./currencies";
import journalRouter from "./journal";
import revaluationsRouter from "./revaluations";
import fixedAssetsRouter from "./fixed-assets";
import inventoryRouter from "./inventory";
import payrollRouter from "./payroll";
import advancesRouter from "./advances";
import customersRouter from "./customers";
import suppliersRouter from "./suppliers";
import invoicesRouter from "./invoices";
import paymentsRouter from "./payments";
import bankRouter from "./bank";
import receivablesReportsRouter from "./receivables-reports";
import financialReportsRouter from "./financial-reports";
import reportsExtraRouter from "./reports-extra";
import analyticalReportsRouter from "./analytical-reports";
import openingBalancesRouter from "./opening-balances";
import dashboardRouter from "./dashboard";
import companyRouter from "./company";
import teamRouter from "./team";
import invitationsRouter from "./invitations";
import auditRouter from "./audit";
import fiscalYearsRouter from "./fiscal-years";
import importRouter from "./import";
import supportRouter from "./support";
import adminSupportRouter from "./admin/support";
import superAdminAuthRouter from "./super-admin-auth";
import superAdminRouter from "./super-admin";
import deployWebhookRouter from "./deploy-webhook";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(accountsRouter);
router.use(taxesRouter);
router.use(costCentersRouter);
router.use(currenciesRouter);
router.use(journalRouter);
router.use(revaluationsRouter);
router.use(fixedAssetsRouter);
router.use(inventoryRouter);
router.use(payrollRouter);
router.use(advancesRouter);
router.use(customersRouter);
router.use(suppliersRouter);
router.use(invoicesRouter);
router.use(paymentsRouter);
router.use(bankRouter);
router.use(receivablesReportsRouter);
router.use(financialReportsRouter);
router.use(reportsExtraRouter);
router.use(analyticalReportsRouter);
router.use(openingBalancesRouter);
router.use(dashboardRouter);
router.use(companyRouter);
router.use(teamRouter);
router.use(invitationsRouter);
router.use(auditRouter);
router.use(fiscalYearsRouter);
router.use(importRouter);
router.use(supportRouter);
router.use(adminSupportRouter);
// HG website public routes must be mounted BEFORE superAdminRouter.
// superAdminRouter has a global router.use(requireSuperAdmin) that
// intercepts ALL requests and returns 401 for unauthenticated users.
// Mounting HG routes first ensures they are handled before hitting that gate.
router.use(articlesRouter);
router.use(settingsRouter);
router.use(servicesRouter);
router.use(packagesRouter);
router.use(leadsRouter);
router.use(caseStudiesRouter);
router.use(uploadsRouter);
router.use(socialPostsRouter);
router.use(aiRouter);
router.use(deployWebhookRouter);
router.use(superAdminAuthRouter);
router.use(superAdminRouter);

export default router;
