// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chart-of-accounts/ChartOfAccounts.tsx": () => import("../components/mockups/chart-of-accounts/ChartOfAccounts.tsx"),
  "./components/mockups/accounting-dashboard/Dashboard.tsx": () => import("../components/mockups/accounting-dashboard/Dashboard.tsx")
};
